from tflite_support import metadata_writers

ImageClassifierWriter = metadata_writers.MetadataWriter
_MODEL_PATH = "model_unquant.tflite"
_LABEL_FILE = "labels.txt"
_SAVE_TO_PATH = "metadata_legume.tflite"
_INPUT_NORM_MEAN = 127.5
_INPUT_NORM_STD = 127.5

# Create the metadata writer.
writer = metadata_writers.ImageClassifierWriter.create_for_inference(
    metadata_writers.load_file(_MODEL_PATH), [_INPUT_NORM_MEAN], [_INPUT_NORM_STD],
    [_LABEL_FILE])

# Verify the metadata generated by metadata writer.
print(writer.get_metadata_json())

# Populate the metadata into the model.
metadata_writers.save_file(writer.populate(), _SAVE_TO_PATH)
