from collections import defaultdict

whitelistLegume = [
    'pepene',
    'pepeni',
    'rubarba',
    'banane',
    'banana',
    'cartofiori',
    'castane',
    'muguri',
    'merisor',
    'platou',
    'carambola',
    'tamarillo',
    'catina',
    'sano vita',
    'nectarine',
    'hrean',
    'germeni',
    'salvie',
    'fistic',
    'alune walnuts',
    'caju',
    'floarea soarelui',
    'cirese',
    'lemongrass',
    'kumquats',
    'pastarnac',
    'mangustan',
    'stafide',
    'seminte',
    'pomelo',
    'porumb',
    'arahide',
    'migdale',
    'caise',
    'ananas',
    'pere',
    'avocado',
    'pepene galben',
    'capsuni romanesti',
    'capsuni',
    'clementine',
    'coacaze rosii',
    'fructul pasiunii',
    'grapefruit rosu',
    'lamai',
    'limes',
    'mandarine',
    'mango',
    'mix mere',
    'mere rosii',
    'mere',
    'zmeura',
    'kiwi',
    'afine',
    'lamai',
    'portocale',
    'avocado',
    'mure',
    'nuca cocos',
    'papaya',
    'pepene verde',
    'physalis',
    'piersici',
    'portocale',
    'struguri albi seedless',
    'struguri roze seedless',
    'rodii',
    'afine',
    'ciuperci galbiori uscati gradina padurii',
    'curmale jasmin',
    'curmale',
    'ghebe',
    'goji',
    'merisoare uscate',
    'mix fructe',
    'prune noberasco',
    'prune uscate',
    'amestec fructe nuci',
    'smochine',
    'rosii cherry alungite',
    'rosii cherry',
    'ciuperci champignon',
    'ardei rosu california',
    'andive',
    'ardei kapia rosu',
    'broccoli',
    'castraveti fabio',
    'ardei gras bianca',
    'varza rosie',
    'vinete',
    'conopida',
    'rosii ciorchine import',
    'praz',
    'ceapa verde romaneasca',
    'usturoi alb',
    'ceapa rosie',
    'ridichi rosii',
    'castraveti cornichon',
    'dovlecei',
    'cartofi albi',
    'cartofi dulci',
    'ceapa galbena',
    'ardei iute verde',
    'castraveti cornichon',
    'ceapa galbena',
    'ciuperci champignon brune',
    'ciuperci champignon',
    'ciuperci grill',
    'ciuperci',
    'ciuperci pleurotus',
    'dovleac dovlecei',
    'fasole alba',
    'fasole pestrita',
    'fenicul',
    'ghimbir',
    'gulii',
    'linte rosie',
    'loboda',
    'morcovi',
    'naut',
    'patrunjel radacina',
    'rosii cherry',
    'rosii ciorchine',
    'rosii',
    'sparanghel',
    'telina apio',
    'telina radacina',
    'usturoi',
    'cartofi pentru salata',
    'mix legume',
    'arpacas',
    'broccoli',
    'fasole alba',
    'lintee',
    'naut',
    'linte',
    'fasole rosie',
    'fasole pestrita',
    'apio',
    'dressing eisberg',
    'dressing',
    'spanac',
    'rucola',
    'mix salata endivia mix eisberg',
    'frunze fetica',
    'fetica',
    'salata',
    'batavia baby',
    'spanac',
    'salata verde',
    'mix salata',
    'rucola ambalata',
    'salata eisberg',
    'rucola',
    'spanac',
    'cimbru',
    'leustean',
    'marar',
    'rozmarin',
    'oregano',
    'menta',
    'coriandru',
    'cimbru',
    'chives',
    'tarhon',
    'busuioc',
    'plante',
]

occurrences = defaultdict(int)

whitelistCarne = [
    'carnaciori',
    'sardeluta',
    'caracatita',
    'piept pui dezosat',
    'pulpa pulpe pui inferioara',
    'pulpa pulpe pui superioara',
    'aripi pui sectionate fara varf',
    'aripi sectionate',
    'aripi pui fara varf',
    'aripi pui aripioare',
    'carne tocata pui',
    'ciocanele',
    'cocosel',
    'copanele',
    'file pui inner',
    'gaturi pui',
    'pui',
    'piept pui os',
    'aripi pui',
    'piept pui dezosat pouce fara piele',
    'piept pui dezosat',
    'pipote inimi pui',
    'pipote inimi pui',
    'pui grill',
    'pulpa pui spate',
    'pulpe pui dezosate piele',
    'pulpe pui',
    'pulpe pui superioare dezosate fara piele',
    'aripi pui',
    'pulpe inferioare pui',
    'pulpe inferioare pui pouce',
    'aripi pui sectionate',
    'ficat pui',
    'inner pui',
    'piept pui dezosat fara piele',
    'piept pui',
    'pipote inimi pui',
    'pui grill',
    'pulpe inferioare pui',
    'pulpe spate',
    'snitel pui',
    'pulpe superioare pui dezosate fara piele',
    'spinari pui',
    'pulpe pui inferioare',
    'piept pui dezosat fara piele',
    'inner pui',
    'pulpe inferioare pui',
    'aripi pui sectionate',
    'piept pui dezosat fara piele',
    'ficat pui',
    'pulpe pui fara piele dezosate',
    'pulpe pui inferioare',
    'pui grill',
    'aripi curcan',
    'curcan',
    'piept curcan',
    'pulpa inferioara curcan',
    'pulpa superioara curcan dezosata',
    'pulpa superioara curcan',
    'curcan',
    'mici dedulesti carne porc vita integra',
    'spata porc fara os',
    'carne tocata porc',
    'carnati chipolatas',
    'carne tocata',
    'mate porc subtiri m',
    'sorici aripioare porc',
    'urechi porc coapte feliate',
    'burta porc',
    'carne tocata porc manzat',
    'coaste porc marinate edenia',
    'carne tocata porc',
    'coaste porc food glory in sos bbq miere',
    'ceafa porc',
    'ceafa porc fara os feliata',
    'ceafa afumata crud uscata',
    'cotlet porc os condimentat',
    'cotlet porc sorici',
    'porc',
    'mici carne porc vita oaie',
    'mici carne porc vita',
    'mici carne porc',
    'muschiulet porc',
    'piept porc os',
    'pulpa porc fara os',
    'slanina porc afumata',
    'snitel porc',
    'piept porc os',
    'mici porc',
    'cotlet porc fara os',
    'cotlet porc fara os',
    'piept porc os',
    'pulpa porc fara os',
    'carne tocata vita ecologica bio',
    'mici carne vita ecologica bio',
    'piept vita',
    'antricot manzat fara os',
    'carne vita pulled food glory gatita lent',
    'carne tocata manzat',
    'cotlet manzat os',
    'cubulete manzat extra',
    'cubulete manzat',
    'mici carne vita oaie',
    'mici',
    'pulpa manzat fara os',
    'pulpa manzat',
    'rasol manzat os',
    'vrabioara manzat fara os',
    'vrabioara manzat',
    'carne manzat amestec pentru ciorba',
    'antricot manzat fara os',
    'coada manzat',
    'inima manzat',
    'limba manzat',
    'oase maduva manzat',
    'piept manzat os',
    'rasol manzat os',
    'vrabioara manzat',
    'pulpa manzat',
    'carne manzat cubulete',
    'pulpa manzat fara os',
    'manzat',
    'carne tocata vita',
    'somon file',
    'pastrav dezosat',
    'pastrav file edenia',
    'file somon afumat',
    'file hering matinat lamaie salmaris',
    'hering marinat',
    'macrou afumat gastronatura',
    'dorada',
    'pastrav eviscerat',
    'pastrav',
    'macrou marinat bonito',
    'file somon afumat',
    'ton',
    'file macrou afumat',
    'salata icre',
    'icre somon',
    'salata icre',
    'salata icre crap ceapa',
    'salata icre stiuca',
    'salata icre hering somon',
    'salata icre crap',
    'clesti crab',
    'fructe mare',
    'muslitos vici',
    'creveti in ulei usturoi',
    'scoici',
    'inele calamar',
    'porc',
    'fructe mare',
    'macrou',
    'hering',
    'pastrav',
    'vita',
    'mare',
    'manzat',
    'midii',
    'pulpe pui',
    'pui',
    'rata',
    'calamar',
    'somon',
    'peste',
    'vitel',
    'icre',
    'creveti',
]

whitelistMezeluri = [
    'salame',
    'rulada',
    'crenwursti cremwursti',
    'babic',
    'tapas',
    'favourites',
    'slanina',
    'salami',
    'hanul boieresc',
    'carnaciori',
    'tochitura',
    'salam banatean',
    'salam victoria extra',
    'salam ghiudem',
    'salam camembert bell',
    'salam rustika',
    'salam crud uscat fin carne porc curcan marten',
    'salam palaciego',
    'salam victoria',
    'salam sunca taranesca',
    'salam victoria',
    'salam sasesc',
    'salam sasesc',
    'salam vara',
    'salam sinaia',
    'salam chorizo',
    'salam rustic',
    'salam banatean',
    'salam napoli',
    'mini salam sasesc picant',
    'salam uscat',
    'salam porc',
    'salam banatean',
    'salam italian uscat',
    'salam sibiu',
    'salam sinaia',
    'salam victoria extra',
    'salam sunca primo',
    'salam casa stilor',
    'salam vara',
    'salam italian',
    'salam victoria extra',
    'salam chorizo',
    'salam pur porc bell',
    'salam alune padure bell',
    'salam peles',
    'salam sibiu',
    'salam vara uscat extra',
    'salam sibiu',
    'salam presat uscat',
    'salam sinaia',
    'salam banatean',
    'salam sinaia',
    'salam vara extra',
    'salam taranesc sunca',
    'salam sarbesc',
    'salam sandwich toast',
    'salam sarbesc gastro',
    'salam sandwich toast',
    'salam vara',
    'salam casa',
    'salam cerb',
    'salam sunca taranesc',
    'salam curcan',
    'salam sibiu',
    'salam curcan',
    'salam felii',
    'salam trapez invelis mirodenii',
    'salam cerb',
    'salam mangalita',
    'salam sibiu',
    'salam secuiesc',
    'salam sinaia',
    'salam ardelenesc',
    'salam secuiesc',
    'salam banatean',
    'salam banatean',
    'salam caprioara',
    'salam ecologic piper negru',
    'salam iarna pick',
    'salam fuet extra',
    'salam chorizo iberico extra',
    'jambon serrano',
    'salam vara',
    'salam sibiu',
    'mini salam sasesc',
    'salam',
    'muschi file',
    'muschi file afumat',
    'muschi file',
    'muschi tiganesc',
    'muschi file afumat',
    'muschi azuga',
    'muschi tiganesc',
    'muschi file sissi',
    'muschi file',
    'muschi file afumat',
    'ceafa afumata crud uscata',
    'muschi afumat crud uscat',
    'muschi afumat',
    'muschi file',
    'carnati maestro subtiri vid',
    'carnati polonezi carne porc vidati',
    'carnati',
    'crenvursti mini pui pepe',
    'crenvursti pui perutnina',
    'carnati albi',
    'crenvursti mini curcan pepe',
    'hot dog',
    'carnati cabanos extra',
    'carnati sticks pui porc',
    'carnati sticks porc',
    'carnati oltenesti',
    'carnati bere',
    'crenvursti piept pui',

    'carnati sticks',
    'carnati sticks picanti',
    'carnati porc plin carne',

    'crenvursti piept pui',
    'carnati bere',
    'crenvursti porc',
    'crenvursti piept pui',
    'crenvursti carne pasare',
    'crenvursti piept pui',
    'crenvursti porc',
    'carnati caprioara',
    'carnati cerb',
    'carnati mistret',
    'carnati porc',
    'carnati vegani',
    'carnati cerb',
    'carnati mistret',
    'carnati afumati mangalita',
    'carnati picanti pickstick pick sticks',
    'crenvursti clasici',
    'crenvursti carne pui curcan',
    'crenvursti branza',
    'mini chorizo picant',
    'crenvursti',
    'carnati taranesti smithfield',
    'carnati bere',
    'crenvursti piept pui',
    'crenvursti porc extra',
    'sunca feliata pulpa porc sissi',
    'sunca feliata piept pui sissi',
    'sunca taraneasca feliata',
    'sunca piept pui feliata',
    'kaizer morliny vidat',
    'sunca curcan pepe',
    'kaizer extra vid',
    'kaizer afumat vidat saramura',
    'sunca praga feliata',
    'sunca curcan feliata',
    'sunca piept pui',
    'kaizer afumat',
    'sunca pulpa porc sissi',
    'sunca piept pui sissi',
    'sunca praga',
    'sunca piept pui',
    'sunca pui feliata',
    'sunca praga feliata',
    'sunca piept pui',
    'sunca pui feliata',
    'sunca fina curcan',
    'sunca presata piept pui',
    'sunca praga feliata',
    'sunca pui feliata',
    'sunca feliata porc',
    'sunca praga feliata',
    'sunca casa cruda banat bun',
    'sunca feliata piept curcan sissi',
    'parizer piept pui',
    'parizer extra',
    'parizer extra pui',
    'mini parizer pui',
    'parizer pasare primo',
    'parizer',
    'parizer piept pui',
    'parizer porc pick',
    'bacon',
    'jambon curcan ifantis',
    'bacon',
    'bacon',
    'jambon piept curcan sissi',
    'bacon',
    'bacon crud uscat',
    'bacon mic dejun',
    'jambon porc felii masa in romania',
    'jambon curcan',
    'bacon afumat',
    'bacon crud ringa felii',
    'jambon serrano espina',
    'jambon pouce',
    'piept taranesc',
    'pastrama pulpa pui prodprosper vid',
    'pastrama piept pui banat bun',
    'gusa afumata',
    'oase garf afumate',
    'sunculita porc vidata',
    'ciolan afumat',
    'piept pui vidat',
    'hamburger carne vita ecologica bio',
    'piept pui pepe',
    'piept pui piper',
    'piept pui afumat slim fit',
    'mortadella',
    'mortadella pasare',
    'prosciutto crudo abraham',
    'crema tartinabila carne pasare',
    'lebar ifantis',
    'pasta ficat pui',
    'toba curcan',
    'felii vegetale mortadella',
    'sunculita taraneasca',
    'cotlet haiducesc',
    'cotlet haiducesc felii',
    'pastrama cerb',
    'pastrama mistret',
    'felii sunci',
    'untura mangalita',
    'jumari mangalita',
    'pasta jumari mangalita',
    'pastrama afumata feliata',
    'parizer taranesc ardei zimbo',
    'lebar banat bun',
    'piept curcan extrafin espina',
    'pate banat bun',
    'pate ficat rata',
    'pate ficat pui pepe',
    'pate fin zimbo',
    'pate',
    'toba',
    'scarita boiereasca masa',
    'carne garnita masa',
    'pastrama piept pui',
    'cotlet haiducesc',
    'icre',
    'sunca pui',
    'sunca curcan',
    'sunca porc',
    'parizer',
    'crenvusti',
    'coaste',
    'carnati',
    'jambon',
    'kaiser',
    'muschi',
    'sunca',
    'carnati',
    'carnacior',
    'porc',
    'pui',
    'curcan',
]

whitelistLactate = [
    'oua fierte vopsite miketi',
    'oua gaina',
    'oua gaina albatros',
    'oua gaina agricola',
    'oua gaina toneli',
    'oua paste fierte vopsite',
    'oua gaina agricola',
    'oua gaina regalina',
    'oua gaina',
    'oua',
    'rama',
    'iaurtul',
    'hanul boieresc',
    'delma',
    'tiramisu',
    'cappuccino',
    'perle',
    'lapte condensat maresi',
    'bautura lapte ciocolata muller',
    'lapte capra',
    'lapte consum monor',
    'lapte consum napolact',
    'lapte vaca',
    'lapte vaca bio napolact',
    'lapte semidegresat bio ladorna',
    'lapte consum ladorna',
    'lapte vaca napolact',
    'lapte ciocolata ladorna',
    'lapte semidegresat napolact fara lactoza',
    'lapte consum zuzu',
    'lapte semidegresat napolact fara lactoza',
    'lapte integral zuzu',
    'lapte consum olympus bogat in proteine',
    'lapte ecologic vaca artesana',
    'lapte capra olympus',
    'lapte bivolita colectar',
    'lapte consum bio napolact',
    'lapte consum bio napolact',
    'lapte consum covalact',
    'lapte consum laptaria caimac',
    'lapte consum prodlacta',
    'lapte consum zuzu',
    'lapte semidegresat ladorna fara lactoza',
    'lapte semidegresat ladorna fara lactoza',
    'lapte semidegresat zuzu',
    'lapte pentru cafea meggle',
    'lapte pentru cafea milram',
    'lapte pentru cafea zott',
    'lapte batut',
    'lapte consum',
    'lapte consum uht ladorna',
    'lapte uht barista meggle',
    'lapte uht muller',
    'lapte pentru cafea uht zuzu barista',
    'lapte uht muller',
    'lapte capra uht andechser natur',
    'lapte uht ladorna',
    'lapte cacao zuzu fit',
    'lapte consum uht fulga',
    'lapte vanilie zuzu fit',
    'lapte consum uht napolact',
    'lapte semidegresat uht',
    'lapte integral uht',
    'lapte cacao uht fulga',
    'lapte integral uht prodlacta',
    'lapte pentru cafea uht delaco',
    'lapte uht bio salzburgmilch',
    'lapte semidegresat uht prodlacta',
    'telemea vaca delaco in saramura',
    'telemea vaca huedin napolact',
    'telemea vaca olympus',
    'telemea vaca covalact',
    'telemea vaca hochland',
    'telemea vaca natur hochland',
    'telemea vaca natur hochland',
    'telemea vaca light hochland',
    'telemea vaca hochland',
    'telemea vaca president',
    'telemea vaca maturata delaco in saramura',
    'telemea vaca napolact proaspata',
    'telemea vaca maturata solomonescu',
    'telemea vaca mirdatod ibanesti',
    'telemea vaca',
    'telemea vaca hochland',
    'telemea oaie napolact',
    'telemea oaie',
    'cascaval dalia therezia',
    'cascaval afumat delaco',
    'cascaval delaco sofia',
    'cascaval emmentaler delaco',
    'cascaval napolact',
    'cascaval delaco desenvis',
    'cascaval emmentaler goldsteig',
    'cascaval bio napolact',
    'cascaval felii bio napolact',
    'cascaval napolact',
    'cascaval delaco desenvis',
    'cascaval emmental paysan breton',
    'cascaval napolact',
    'cascaval felii napolact',
    'cascaval afumat desenvis delaco',
    'cascaval dobrogea',
    'cascaval capra five continents',
    'cascaval fara lactoza',
    'cascaval dalia covalact',
    'cascaval penteleu covalact',
    'cascaval rucar covalact',
    'cascaval clasic felii hochland',
    'cascaval clasic hochland',
    'cascaval hochland',
    'cascaval carpati five continents',
    'cascaval clasic hochland',
    'cascaval afumat hochland',
    'cascaval nature hochland',
    'cascaval clasic hochland',
    'cascaval delaco sofia',
    'cascaval cheddar delaco desenvis',
    'cascaval dalia covalact',
    'cascaval dalia five continents',
    'cascaval penteleu gordon',
    'cascaval afumat impletit therezia',
    'cascaval therezia dotti',
    'cascaval dalia solomonescu',
    'cascaval delaco sofia',
    'cascaval felii lacto food',
    'cascaval lapte vaca mirdatod ibanesti',
    'cascaval',
    'cascaval afumat rotund romfulda',
    'cascaval emmentaler felii delaco senvis',
    'cascaval afumat',
    'cascaval clasic',
    'cascaval delaco',
    'cascaval felii delaco',
    'cascaval emmental president felii',
    'cascaval felii',
    'cascaval montan ibanesti mirdatod',
    'cascaval pentru sandwich rucar',
    'cascaval afumat hochland',
    'cascaval clasic hochland',
    'cascaval rucar',
    'cas vaca',

    'branza topita smantana hochland',
    'branza topita minusl felii fara lactoza',
    'branza topita hochland',

    'branza topita smantana albalact',
    'branza topita del natur triunghiuri',
    'branza topita smantana delaco apetito felii',
    'branza topita'
    'branza pufoasa smantana delaco',
    'crema branza natur simply',
    'branza pufoasa verdeata delaco',
    'crema branza verdeturi simply',
    'branza cremoasa hochland',
    'crema branza olympus',
    'branza pufoasa somon delaco',
    'branza pufoasa delaco fara lactoza',
    'crema branza philadelphia original',
    'crema smantana gordon',
    'crema branza hrean almette proaspata',
    'crema branza ceapa verde almette proaspata',
    'crema branza hochland',
    'crema branza verdeata hochland',
    'branza cremoasa president',
    'crema branza almette',
    'almette',
    'crema branza smantana delaco',
    'crema branza delaco junior',
    'crema branza colline capra',
    'crema branza simpla philadelphia',
    'crema tartinabila violife',
    'mozzarella feliata hochland',
    'branza cottage clasic delaco',
    'branza grasa vaci prodlacta proaspata',
    'branza cottage light delaco',
    'branza vaci covalact proaspata',
    'branza vaci covalact proaspata',
    'branza vaca',
    'branza fagaras sanlacta',
    'branza vaci delaco proaspata',
    'branza casa bio covalact',
    'branza vaci delaco proaspata',
    'branza vaci smantana fagaras',
    'mozzarella mini galbani bilute',
    'mozzarella galbani',
    'mozzarella galbani',
    'cas vaca afumat solomonescu',
    'mozzarella delaco fresca',
    'branza casa covalact strop sare',
    'branza casa covalact',
    'mozzarella delaco',
    'mascarpone',
    'mozzarella gourmet delaco',
    'branza alba vaca delaco junior',
    'branza vaci smantana fagaras proaspata',
    'branza capra',
    'branza proaspata rasa pecorino',
    'urda lapte vaca mirdatod ibanesti',
    'mozzarella bivolita zanetti campana',
    'mozzarella felii delaco desenvis',
    'mozzarella gourmet delaco',
    'mozzarella',
    'branza vaci fagaras raraul',
    'branza feta olympus in saramura',
    'branza camembert delaco',
    'branza brie delaco',
    'baton vegetal inedit tofu',
    'margele branza hochland',
    'branza vaci danonino piure zmeura banane',
    'branza alba vaci delaco junior',
    'branza aperitiv delaco mix',
    'branza ile france',
    'branza camembert',
    'branza cedar felii delaco desenvis',
    'cedar',
    'branza presata',
    'branza brie president',
    'branza brie paysan breton',
    'branza aperitiv delaco aperifrais provence',
    'branza mucegai kaserei champignon triunghi',
    'branza mucegai albastru bergarder gran bavarese',
    'branza burduf covalact',
    'branza rotita bergader bavaria blu',
    'branza feta bio andechser natur',
    'branza burduf',
    'branza gouda andechser natur',
    'branza feta olympus',
    'branza maturata',
    'branza feliata mizo trappist fara lactoza',
    'branza mucegai albastru st clemens',

    'branza pentru salata arla danish',
    'branza camembert president naturalny',
    'camembert',
    'bulgarasi branza usoara covalact',
    'branza feta hochland',
    'margele branza hochland fara lactoza',
    'branza feta mediterranea',
    'branza feta president',
    'feta',
    'branza burduf ferma',
    'cas dulce',
    'branza grana padano bio agriform',
    'branza graviera trufa neagra mediterranea',
    'branza grana',
    'branza cottage proteina arla',
    'branza grana padano galbani',
    'branza ricotta brimi',
    'parmezan reggiano zanetti',
    'branza grana padano zanetti pentru paste',
    'branza grana padano zanetti',
    'branza halloumi',
    'halloumi',
    'branza pecorino romano dop zanetti',
    'pecorino',
    'branza grana rasa padano agriform',
    'branza grana padano agriform cubulete',
    'branza grana rasa primo agriform mix',
    'branza grana',
    'branza meze pentru gratar olympus',
    'gorgonzola',
    'branza olandeza leerdammer original',
    'branza rasa pentru paste hochland',
    'sos branza fiesta',
    'branza rasa pentru pizza hochland',
    'branza tierra horezu five continents fermentata',
    'felii vegane',
    'margele branza hochland',
    'parmezan reggiano galbani',
    'snacksuri branza gran biraghi batoane',
    'sos branzeturi cascina lia',
    'cheddar',
    'mozzarella',
    'specialitate',
    'sticksuri branza zott original',
    'tofu afumat in saramura inedit',
    'tofu in saramura inedit',
    'tofu in saramura inedit ardei',
    'tofu in saramura inedit chimen',
    'tofu in saramura inedit marar',
    'tofu simplu inedit fara sare',
    'telemea bivolita rustic',
    'branza burduf napolact',
    'branzica',
    'iaurt grecesc olympus',
    'iaurt grecesc natur bio olympus',
    'iaurt bio napolact',
    'iaurt covalact',
    'iaurt bio napolact',
    'iaurt natur activia',
    'iaurt bio covalact',
    'muller',
    'iaurt granola mix seminte bio napolact',
    'iaurt grecesc muller',
    'sos salata',
    'nestle',
    'espresso',
    'iaurt grecesc kolios',
    'iaurt grecesc olympus',
    'iaurt napolact bio',
    'iaurt grecesc semidegresat olympus',
    'iaurt cremos bio napolact',
    'iaurt numa bun napolact',
    'iaurt cremos napolact',
    'iaurt covalact',
    'iaurt numa bun napolact',
    'iaurt cremos covalact',
    'iaurt bio covalact',
    'iaurt natural danone',
    'iaurt natural danone',
    'iaurt grecesc danone',
    'iaurt natural zuzu',
    'iaurt natural zuzu',
    'iaurt natural zuzu bifidus stors',
    'iaurt natural zuzu stors',
    'iaurt grecesc natural zuzu divin',
    'iaurt grecesc olympus',
    'iaurt grecesc natur olympus',
    'iaurt olympus',
    'iaurt grecesc olympus',
    'iaurt natural laptaria caimac',
    'iaurt laptaria caimac',
    'iaurt natural lapte vaca artesana',
    'iaurt cremos lapte bivolita colectar',
    'iaurt natur',
    'actimel',
    'iaurt mic dejun activia fulgi cereale',
    'iaurt mic dejun activia fulgi cereale capsuni',
    'iaurt grecesc muller arome asortate',
    'iaurt piersici danone cremosso',
    'iaurt visine cremosso',
    'iaurt stracciatella danone cremosso',
    'iaurt mix fructe muller',
    'iaurt cremos muller',
    'iaurt bilute ciocolata muller',
    'iaurt capsuni danone delicios',
    'iaurt musli capsuni activia',
    'iaurt proteic banane unt arahide yopro',
    'iaurt fructe zott',
    'iaurt capsuni zott',
    'iaurt capsuni muller cremos',
    'iaurt piersici caise muller',
    'iaurt mure zmeura muller',
    'iaurt cirese muller cremos',
    'iaurt crema muller diverse arome',
    'iaurt crema muller diverse sortimente',
    'iaurt fructe muller',
    'iaurt stracciatella muller',
    'iaurt cremos alune padure muller',
    'iaurt proteine muller zero ciocolata',
    'bautura proteica muller aroma banane fara zahar',
    'iaurt biscuiti danone delicios',
    'iaurt mic dejun activia fulgi porumb',
    'iaurt baut danonino piure capsuni',
    'iaurt baut activia kiwi capsuni',
    'iaurt baut activia zmeura rodie',
    'iaurt cereale nuci ovaz activia',
    'iaurt piure capsuni banane danonino',
    'iaurt baut yopro zmeura capsuni',
    'iaurt sanlacta',
    'iaurt yopro',
    'iaurt visine zuzu',
    'iaurt piersici caise zuzu',
    'iaurt banane zuzu',
    'iaurt piersici capsuni zuzu',
    'iaurt baut zuzu bifidus mango para',
    'iaurt baut zuzu bifidus caise piersici',
    'iaurt fructe zuzu aroma fructe padure',
    'iaurt grecesc olympus coacaze',
    'iaurt grecesc rodie zmeura olympus',
    'iaurt grecesc',
    'iaurt capsuni bio napolact',
    'iaurt fructe padure bio napolact',
    'smantana muller',
    'smoothie afine banane zuzu',
    'smoothie capsuni piersici zuzu',
    'sana',
    'iaurt baut napolact',
    'iaurt baut natur activia',
    'lapte batut napolact',
    'iaurt baut napolact',
    'lapte batut covalact',
    'lapte covasit covalact',
    'iaurt baut covalact',
    'iaurt baut natural danone',
    'iaurt baut activia fibre',
    'iaurt baut natural danone',
    'iaurt baut sanlacta',
    'iaurt baut natural zuzu',
    'iaurt',
    'lapte batut romfulda',
    'ayran danone',
    'ayran laptaria caimac',
    'lapte batut bio napolact',
    'lapte batut rustic',
    'lapte batut covalact',
    'kefir ecologic lapte vaca artesana',
    'kefir muller',
    'kefir olympus',
    'chefir bio napolact',
    'chefir usor covalact',
    'chefir',
    'latte',
    'prajitura kinder felie lapte',
    'bautura latte macchiato muller',
    'bautura espresso machiatto muller',
    'orez lapte muller',
    'budinca muller ciocolata topping vanilie',
    'orez lapte muller riso aroma visine',
    'orez ciocolata muller',
    'budinca muller sos cirese',
    'sos gatit',
    'baton pufos milka lapte ciocolata',
    'desert kinder pingui',
    'desert kinder maxi king',
    'budinca zott liegeois ciocolata frisca',
    'budinca vanilie ciocolata paula vanilla',
    'desert paula pudding vanilie',
    'budinca proteica dr.oetker vanilie',
    'bautura lapte muller',
    'budinca andechser natur gust ciocolata ecologica',
    'desert danette crema zahar ars',
    'mousse',
    'cafea',
    'bautura lapte cafea frappuccino starbucks aroma vanilie',
    'bautura lapte cafea frappuccino starbucks',
    'bautura lapte cafea frappuccino starbucks aroma caramel',
    'bautura frappe zuzu',
    'crema pentru desert voila',
    'budinca ciocolata frisca zuzu dolce',
    'crema pentru desert voila',
    'budinca vanilie frisca zuzu dolce',
    'budinca ciocolata',
    'budinca',
    'desert ciocolata danette',
    'desert aroma vanilie danette',
    'baton branza dots natur dark',
    'baton branza dots natur',
    'branza capra',
    'branza vaca',
    'bautura nesquik shake',
    'desert milk burger',
    'desert',
    'baton cacao ciocolata',
    'orez lapte caramel riso',
    'orez lapte ciocolata alune riso',
    'lapte bio',
    'lapte lactoza',
    'lapte',
    'orez vegan ciocolata riso',
    'smantana gatit ladorna',
    'smantana gatit ladorna',
    'smantana covalact',
    'smantana gatit meggle',
    'smantana bio napolact',
    'smantana napolact',
    'smantana ardeleneasca covalact',
    'smantana napolact',
    'smantana cremoasa muller',
    'smantana albalact',
    'smantana napolact',
    'smantana ardeleneasca covalact',
    'crema pentru gatit uht cucina d oro',
    'smantana gatit ladorna',
    'crema pentru gatit uht cucina d oro',
    'crema pentru gatit uht cucina d oro',
    'smantana gatit ladorna',
    'crema vegetala pentru gatit gran cucina',
    'smantana casa buna',
    'smantana casa buna',
    'crema vegetala pentru gatit gran cucina',
    'crema vegetala pentru gatit gran cucina',
    'smantana pentru frisca sanlacta',
    'smantana sanlacta',
    'smantana albalact',
    'smantana consum albalact',
    'smantana albalact',
    'smantana albalact',
    'smantana naturala monor',
    'smantana proaspata laptaria caimac',
    'smantana covalact',
    'smantana rustic',
    'smantana covalact',
    'smantana gatit olympus',
    'smantana gatit olympus',
    'smantana prodlacta',
    'smantana',
    'smantana',
    'frisca lichida uht creme patisserie',
    'crema pentru prajituri meggle',
    'frisca ladorna',
    'frisca uht hulala',
    'frisca lichida uht meggle creme patisserie',
    'frisca',
    'unt arahide go on smooth',
    'unt nesarat president',
    'unt arahide go on crunchy',
    'creminos unt lacto food',
    'unt capra olympus',
    'unt masa napolact',
    'unt masa',
    'unt tartinabil bio olympus capra',
    'unt nesarat lurpak',
    'unt albalact',
    'unt meggle',
    'unt arahide cremos nutline',
    'unt covalact',
    'unt sarat afumat laptaria caimac',
    'unt masa albalact',
    'unt dulce kerrygold',
    'unt lacto food sare mare',
    'unt napolact',
    'unt premium lacto food',
    'unt prodlacta',
    'unt sarat lurpak',
    'unt sarat paysan breton',
    'unt semi sarat president',
    'unt sole',
    'unt tartinabil nesarat president beurre tendre',
    'unt tartinabil nesarat president',
    'unt tartinabil sarat muller',
    'unt',
    'unt irlandez',
    'amestec tartinabil usor sarat lurpak lighter',
    'crema tartinabila alpinesse',
    'crema fagaras',
    'margarina becel original',
    'margarina linco neata',
    'margarina unirea original',
    'proteine',
    'proteina',
    'parmigiano',
    'kinder',
    'gorgogonzola',
]

whitelistBauturiNonalcoolice = [
    'zuzu',
    'sos salata',
    'apa plata aqua carpatica kids',
    'apa plata dorna izvorul alb',
    'apa plata carpatina light',
    'apa plata izvor aquavia',
    'apa plata bucovina',
    'apa plata izvor aquavia',
    'apa plata aqua carpatica',
    'apa plata minerala naturala dorna izvorul alb',
    'apa plata vittel sport cap',
    'apa plata izvor aquavia',

    'apa plata aqua carpatica',
    'apa plata zizin',
    'apa plata perla harghitei',
    'apa plata zizin',
    'apa plata aqua carpatica',
    'apa plata perla harghitei',
    'apa plata aquatique',
    'apa plata izvorul dintre brazi',

    'apa plata carpatina',
    'apa plata borsec',

    'apa plata alcalia velingrad',
    'apa plata zizin',
    'apa plata borsec',
    'apa plata borsec',
    'apa plata minerala light san benedetto',
    'apa plata vittel',
    'apa plata smart water',
    'apa plata minerala carpatina',
    'apa plata oligominerala aquatique',
    'apa plata borsec',
    'apa plata naturala',
    'apa plata minerala naturala perla harghitei',
    'apa plata minerala keia',
    'apa plata minerala izvorul zaganului',
    'apa plata izvorul dintre brazi',
    'apa plata carpatina',
    'apa plata azuga',
    'apa plata azuga',
    'apa plata minerala san benedetto',
    'apa plata naturala dorna izvorul alb',
    'apa plata smart water',
    'apa plata vittel',
    'apa plata vittel',
    'apa plata zizin',
    'apa plata izvor',
    'apa plata izvor',
    'apa plata aquavia',
    'apa plata aqua carpatica',
    'apa plata izvor azuga',
    'apa carbogazoasa minerala aqua carpatica',
    'apa minerala naturala',
    'apa carbogazoasa minerala aqua carpatica',
    'apa carbogazoasa poiana negri',
    'apa carbogazoasa minerala naturala dorna',
    'apa carbogazoasa minerala perla harghitei',
    'apa carbogazoasa minerala borsec',
    'apa carbogazoasa minerala perla harghitei',
    'apa carbogazoasa partial perla harghitei',
    'apa carbogazoasa minerala naturala dorna',
    'apa carbogazoasa poiana negri cumpatata',
    'apa carbogazoasa minerala borsec',
    'apa carbogazoasa minerala borsec',
    'apa carbogazoasa minerala naturala tusnad',
    'apa carbogazoasa izvorul ascuns',
    'apa carbogazoasa minerala aqua carpatica',
    'apa carbogazoasa minerala aqua carpatica',
    'apa minerala naturala slab carbogazoasa tusnad',
    'apa carbogazoasa minerala izvorul minunilor',
    'apa carbogazoasa minerala zizin',
    'apa carbogazoasa minerala harghita',
    'apa carbogazoasa minerala',
    'apa carbogazoasa minerala bucovina',
    'apa carbogazoasa carpatina',
    'apa carbogazoasa',
    'apa carbogazoasa minerala san benedetto',
    'apa carbogazoasa partial perla harghitei',
    'apa carbogazoasa izvor',
    'apa carbogazoasa izvor',
    'apa carbogazoasa minerala naturala tusnad',
    'apa carbogazoasa minerala aqua carpatica',
    'apa aromatizata vitamin aqua b zero',
    'apa aromatizata vitamin aqua ca zero',
    'apa aromatizata vitamin aqua c zero',
    'apa aromatizata vitamin aqua zero',
    'apa aromatizata vitamin aqua b',
    'apa aromatizata vitamin aqua c',
    'apa aromatizata vitamin aqua ca',
    'apa aromatizata vitamin aqua zn',
    'apa aromatizata vitamin aqua',
    'apa vitamine brainia ginseng fructul pasiunii rodie',
    'apa vitamine brainia cafea verde aroma zmeura capsuni',
    'apa fructata sevia zmeura magneziu',
    'apa fructata lamaie bucovina',
    'apa aloe vera pure plus detox aroma mar castravete',
    'apa fructata piersica bucovina',
    'apa fructata mar bucovina',
    'apa fructata sevia lamaie magneziu',
    'apa vitamine oshee zero zahar',
    'apa vitamine oshee magnesium',
    'apa vitamine oshee vitamins minerals',
    'apa aroma tedi',
    'apa fructata aroma lamaie fontea',
    'apa aloe vera pure plus detox aroma lamaie calamansi',
    'apa aromatizata vitamin aqua',
    'fanta portocale',
    'fanta',
    'bautura cabogazoasa sprite',
    'pepsi max taste',
    'pepsi regular',
    'pepsi twist',
    'aqua carpatica zmeura',
    'aqua carpatica piersici mango',
    'aqua carpatica soc capsuni',
    'aqua carpatica lamaie verde menta',
    'aqua carpatica',
    'apa tonica castravete verde pepene rosu double dutch',
    'mirinda',
    'pepsi',
    'aroma struguri rodie mirinda',
    'aroma struguri rodie mirinda',
    'mirinda',
    'suc lamaie pepsi cola twist',
    'fara zahar pepsi cola max',
    'mirinda grepfruit roz',
    'coca-cola zero',
    'coca-cola',
    'mirinda grepfruit roz',
    'mirinda',
    'coca-cola zero',
    'mountain dew',
    'pepsi max taste',
    'pepsi twist',
    'pepsi vintage',
    'pepsi cola',
    'pepsi',
    'pepsi',
    'bautura racoritoare carbogazoasa san benedetto piersici zero zahar',
    'bautura racoritoare carbogazoasa san benedetto ghimbir zero zahar',
    'bautura racoritoare pepsi cola twist gust lamaie',
    'schweepes grepfrut roz',
    'fanta portocale zero zahar',
    'pop cola classic',
    'pop cola zero',
    'aroma grapefruit',
    'aroma limonada',
    'aroma rodie portocale',
    'aroma portocale rosii',
    'aroma portocale',
    'aroma clementine',
    'bautura racoritoare carbogazoasa royal crown cola fara zahar',
    'aroma portocale mirinda',
    'bautura racoritoare carbogazoasa up lamaie lime zero zahar',
    'schweppes pink tonic style',
    'sprite',
    'capri sun bubbles portocale',
    'schweppes mandarin',
    'schweppes tonic water',
    'capri sun bubbles zmeura',
    'schweppes bitter lemon',
    'schweppes zero',
    'sprite',
    'figa fiori di guarana',
    'royal crown cola fara zahar',
    'royal crown cola original',
    'schweppes tonic water',
    'bautura tonica evervess',
    'aroma fructe rosii san benedetto zero',
    'fanta grapefruit roz zero zahar',
    'up lime',
    'fanta madness',
    'fanta orange portocale',
    'sprite',
    'schweppes mandarin',
    'aroma grapefruit roz bundaberg',
    'aroma fructul pasiunii bundaberg',
    'mango fanta zero zahar',
    'schweppes mandarine',
    'schweppes bitter lemon',
    'giusto',
    'schweppes pink tonic style',
    'apa tonica double dutch skinny',
    'apa tonica merisor ghimbir double dutch',
    'natural cola ritchie',
    'schweppes bitter lemon',
    'sprite',
    'sprite',
    'robby bubble',
    'aroma piersici frutti',
    'aroma pere frutti',
    'aroma grapefruit frutti',
    'aroma portocale fruti',
    'frutti tutti frutti',
    'tutti frutti adria',
    'suc piersici adria',
    'coca-cola zero lime',
    'coca-cola',
    'fara cofeina coca-cola',
    'pop cola zero lamaie lime',
    'lamaie lime pop cola',
    'lamaie lime pop cola zero',
    'lamaie lime pop cola',
    'aroma cola royal crown cola',
    'coca-cola',
    'coca-cola zero',
    'pop cola zero',
    'pop cola classic',
    'pop cola zero',
    'pop cola classic',
    'dr.pepper',
    'coca-cola',
    'coca-cola zero',
    'coca-cola',
    'coca-cola',
    'fanta madness',
    'pepsi',
    'coca-cola zero lime',
    'pepsi',
    'coca-cola zero',
    'coca-cola',
    'coca-cola',
    'gust lamaie pepsi cola twist',
    'coca-cola',
    'coca cola',
    'aroma uludag',
    'coca-cola zero',
    'coca-cola',
    'schweppes mojito',
    'aroma lamaie schweppes',
    'adria cola',
    'bautura racoritoare carbogazoasa san benedetto allegra zero zahar',
    'bautura racoritoare carbogazoasa san benedetto limone zero zahar',
    'schweepes grepfrut roz',
    'bautura racoritoare carbogazoasa candy can',
    'aroma cola royal crown cola',
    'bautura racoritoare carbogazoasa tailor indian tonic',
    'bautura racoritoare carbogazoasa tailor mojito',
    'bautura racoritoare carbogazoasa tailor rum cola',
    'bautura racoritoare carbogazoasa tailor elderflower',
    'bautura racoritoare carbogazoasa tailor passion martini',
    'bautura racoritoare carbogazoasa tailor rose lemonade',
    'bautura racoritoare carbogazoasa tailor gin tonic',
    'capri sun bubbles cirese',
    'bautura racoritoare carbogazoasa chupa chups',
    'bautura racoritoare carbogazoasa okf aloe vera sparkling original',
    'bautura racoritoare carbogazoasa okf vitamin c lemon sparkling',
    'royal crown cola original',
    'royal crown cola fara zahar',
    'cola franklin sons',
    'apa tonica soc castravete franklin sons',
    'cas',
    'pepsi-cola',
    'lamaie lurisia',
    'aroma portocale rosii lurisia',
    'bautura racoritoare carbogazoasa figa suc fructe',
    'bautura fara alcool piersici bambino party copii',
    'sampanie copii',
    'aloe vera afine queen',
    'aloe vera pure nature queen',
    'aloe vera zero queen',
    'aloe vera ananas queen',
    'aloe vera mango queen',
    'aloe vera rodie queen',
    'mere visine ciao',
    'mere zmeura ciao',
    'suc mere verzi ciao',
    'nestea',
    'piersica nestea',
    'capri sun mystic dragon',
    'capri sun',
    'suc portocale',
    'santal',
    'tedi play',
    'piersici san benedetto',
    'tymbark',
    'tymbark',
    'bautura racoritoare necarbogazoasa pure plus aloe pomegranate',
    'bautura racoritoare necarbogazoasa pure plus aloe original',
    'bautura racoritoare necarbogazoasa dellos',
    'bautura racoritoare necarbogazoasa dellos rodie',
    'bautura racoritoare necarbogazoasa dellos capsuni',
    'cirese yippy',
    'multivitamine yippy',
    'fructe rosii santal',
    'pfanner lamaie',
    'fara zahar pure plus my aloe original',
    'suc piersici san benedetto',
    'suc lamaie san benedetto',
    'ceai verde aloe vera san benedetto',
    'lamaie san benedetto',
    'bautura racoritoare necarbogazoasa dellos limonada zmeura',
    'aloe vera dellos',
    'bautura racoritoare necarbogazoasa dellos mojito',
    'pulpa aloe vera ananas pure plus',
    'bautura racoritoare necarbogazoasa dellos limonada',
    'aloe vera rodii',
    'bautura racoritoare',
    'pulpa aloe vera pure plus',
    'mandarine pfanner',
    'limonada uludag',
    'bautura nacarbogazoasa aloe vera dellos zero',
    'surprise drinks',
    'limonada limolife original',
    'limonada limolife zero',
    'limonada limolife aroma zmeura',
    'banane capsuni prigat',
    'piersici cappy pulpy',
    'ceai negru lamaie lipton ice tea',
    'piersici prigat',
    'ananas tymbark cool',
    'portocale prigat',
    'san benedetto the lamaie',
    'suc piersica lipton ice tea',
    'ceai verde aloe vera san benedetto',
    'mar verde tymbark cool',
    'suc piersici san benedetto',
    'suc portocale prigat',
    'piersici tymbark cool',
    'suc visine prigat',
    'suc zmeura lipton ice tea',
    'portocale tymbark cool',
    'nestea',
    'visine tymbark cool',
    'visine prigat',
    'multivitamine capri sun',
    'limonada prigat',
    'gust mango maracuja capri sun',
    'limonada prigat',
    'lipton ice tea green',
    'bautura racoritoare gatorade cool blue',
    'pulpa aloe vera pure plus',
    'mojito pure plus',
    'pina colada pure plus',
    'tymbark immuno mar lamaie dovleac ghimbir',
    'tymbark immuno portocale fructul pasiunii',
    'tymbark immuno multifruct',
    'sirop agave profructta',
    'mure aronia sirop agave profructta',
    'bautura racoritoare necarbogazoasa okf pepene rosu',
    'pfanner',
    'fara zahar pure plus my aloe original',
    'cirese santal',
    'rodii santal',
    'aroma ananas cocos pfanner',
    'bautura racoritoare necarbogazoasa okf lamaie ghimbir',
    'limonada no lamaie ghimbir merlin',
    'limonada cappy',
    'aloe vera dellos',
    'aloe vera rodii dellos',
    'capsune pepene rosu santal',
    'cirese rodie capri sun',
    'mere',
    'multivitamine capri sun',
    'nuca cocos ananas pure plus',
    'pepene galben yogovera',
    'piersici figo kids',
    'bautura racoritoare lipton ice tea mango fructul pasiunii',
    'limonada capsuni cappy zero zahar',
    'lamai verzi limmi',
    'orez organic riso scotti',
    'limonada lamaie menta cappy',
    'limonada uludag',
    'mere sfecla',
    'limonada no lime menta merlin',
    'limonada no merlin',
    'suc zmeura lipton ice tea',
    'mango ananas nestea',
    'ceai verde lipton ice tea green',
    'suc piersica nestea',
    'suc lamaie nestea',
    'ceai negru piersici lipton ice tea',
    'ceai negru lamaie lipton ice tea',
    'limone san benedetto zero',
    'aroma portocale san benedetto zero',
    'limonada no lamaie ghimbir merlin',
    'lamaie lychee pfanner',
    'portocale rosii pfanner',
    'limonada cappy',
    'mango maracuja pfanner',
    'portocale pfanner',
    'bautura racoritoare necarbogazoasa merlinlemonade no lime mere',
    'tymbark cool pepene galben',
    'tymbark cool fructul dragonului',
    'tymbark cool mar cactus',
    'bautura racoritoare tymbark fizzy portocale mango',
    'bautura racoritoare tymbark fizzy lamaie menta',
    'bautura racoritoare necarbogazoasa dellos aloe vera afine',
    'limonada capsuni cappy zero zahar',
    'pfanner ice tea aroma piersica',
    'piersica cappy pulpy',
    'grapefruit cappy pulpy',
    'portocale cappy pulpy',
    'aloe vera dellos zero',
    'limonada no lime menta merlin',
    'limonada no merlin',
    'piersici fuzetea',
    'piersici fuzetea',
    'lamaie lemongrass fuzetea',
    'fructe padure fuzetea',
    'lime menta fuzetea',
    'lamaie lemongrass fuzetea',
    'lime menta fuzetea',
    'aloe vera mango dellos',
    'suc visine profructta',
    'struguri albi aloe vera tymbark',
    'mar lamaie menta tymbark',
    'zmeura mere menta tymbark',
    'cirese santal',
    'portocale rosii sicilia santal',
    'rodie santal top',
    'grapefruit cappy pulpy',
    'visine santal',
    'mere verzi santal',
    'piersici santal',
    'portocale santal',
    'fructe rosii santal',
    'portocale cappy pulpy',
    'granini',
    'aloe vera dellos',
    'piersici granini',
    'portocale granini',
    'batura necarbogazoasa aroma aloe vera mure mere tymbark',
    'suc piersici san benedetto',
    'suc visine granini',
    'portocale pulpa granini',
    'nectar piersici',

    'ceai menta olympus',
    'ceai piersici olympus',
    'ceai natural lamaie olympus',
    'bautura pentru rehidratare prime hydration blue raspberry',
    'bautura pentru rehidratare prime hydration tropical punch',
    'bautura pentru rehidratare prime hydration strawberry',
    'bautura pentru rehidratare prime hydration ice pop',
    'bautura pentru rehidratare prime hydration meta moon',
    'bautura pentru rehidratare prime hydration lemon lime',
    'suc natural multifructe ciao',
    'suc natural piersici ciao',
    'suc natural portocale ciao',
    'suc catina congelat biocat',
    'suc natural mar verde tymbark',
    'suc natural visine mere tymbark',
    'suc natural mare verzi tymbark',
    'suc natural mere ana are',
    'suc natural mere ana are',
    'suc natural mere pfanner',
    'suc natural mere pfanner',
    'suc natural mere afine ana are',
    'suc natural mere santal',
    'suc natural piersici pfanner',
    'suc natural portocale rosii pfanner',
    'suc natural struguri catina ana are',
    'suc natural mere capsuni banane struguri ana are',
    'suc natural portocale santal',
    'suc natural mere granini',
    'suc natural portocale granini',
    'suc natural mere coacaze artesana',
    'suc natural mere coacaze artesana',
    'suc natural mere portocale morcovi olympus',
    'suc natural portocale olympus',
    'suc natural portocale olympus',
    'suc natural portocale olympus',
    'suc natural mixt fructe legume olympus',
    'suc natural mere artesana',
    'suc natural mere visine artesana',
    'suc mixt fructe olympus',
    'suc mixt fructe legume olympus',
    'suc natural clementine andro',
    'suc natural fructe vitamine olympus',
    'limonada andros',
    'suc natural portocale andros',
    'suc natural grapefruit rosu andros',
    'suc natural morcov olympus',
    'suc natural rodie struguri portocale mere olympus',
    'suc natural mixt fructe olympus',
    'suc natural mere pere ana are',
    'suc natural merisoare santal',
    'suc natural portocale pfanner',
    'suc natural portocale pfanner',
    'suc natural portocale santal',
    'suc natural portocale tymbark',
    'suc natural tomate tymbark',
    'suc natural mere pere',
    'suc natural mere visine',
    'suc natural mere soc',
    'suc natural mere',
    'nectar morcov',
    'nectar pere santal',
    'sirop agave sunny via',
    'sirop artar maple joe',
    'suc natural struguri catina ana are',
    'sirop capsuni laurul',
    'sirop natural soc laurul',
    'sirop natural visine laurul',
    'sirop natural lamaie laurul',
    'suc natural mere lamaie ana are',
    'sirop lamaie menta yo',
    'nectar piersici santal',
    'nectar portocale mango granini',
    'tedi',
    'suc natural struguri visine ana are',
    'sirop capsune',
    'sirop afine',
    'sirop visine',
    'sirop zmeura',
    'sirop soc lamaie',
    'sirop fructe padure',
    'ceai negru piersici lipton ice tea',
    'bautura racoritoare lipton ice tea mango fructul pasiunii',
    'red bull',
    'bautura energizanta burn apple kiwi',
    'bautura energizanta burn original',
    'bautura energizanta mere hell',
    'bautura energizanta piersica burn zero',
    'bautura energizanta hell energy coffee cappuccino',
    'bautura energizanta hell energy coffee latte',
    'bautura energizanta hell energy',
    'bautura energizanta monster ultra paradise',
    'bautura energizanta bull',
    'bautura energizanta monster energy lewis hamilton zero zahar',
    'bautura energizanta pepene monster ultra zero zahar',
    'bautura energizanta fara zahar monster ultra fiesta mango',
    'bautura energizanta baza cafea cappuccino cafemio',
    'bautura energizanta baza cafea macchiato cafemio',
    'bautura energizanta monster mango loco',
    'bautura energizanta bull tropical',
    'bautura energizanta pepene rosu bull',
    'bautura energizanta hell black cherry',
    'bautura energizanta fara zahar monster ultra white',
    'bautura energizanta monster green',
    'bautura energizanta burn original',
    'bautura energizanta fara zahar bull',
    'schweppes',
    'nestea',
    'ice coffee',
    'sirop',
    'frutti fresh',
    'mere',
    'muller',
    'viwa',
    'Nectar',
    'espresso',
    'k-to-go',
    'nestle',
]

whitelistBauturiAlcoolice = [
    'bere beck',
    'bere ursus',
    'wembley',
    'glenlivet',
    'beefeater',
    'cervus'
    'monin',
    'becks',
    'cotnari',
    'via',
    'sarica',
    'bacio',
    'krombacher',
    'mesterul manole',
    'bere alba nefiltrata schofferhofer',
    'bere beckblonda',
    'bere birra moretti',
    'bere birra moretti',
    'bere ciucas',
    'bere ciucas',
    'bere corona extra',
    'bere brau',
    'bere heineken silver',
    'bere indigen sticla',
    'bere ipa edelmeister',
    'bere kozel',
    'bere miller genuine draft',
    'bere nefiltrata corvus sticla',
    'bere peroni',
    'bere peroni',
    'bere nefiltrata nemteana sticla',
    'bere staropramen',
    'bere stella artois',
    'bere timisoreana',
    'pachet bere ciuc premium',
    'bere tuborg',
    'bere ursus',
    'bere bruna gorun sticla',
    'bere bruna guinnes draught',
    'bere bruna leffe',
    'bere bruna paulaner nefiltrata sticla',
    'bere bruna silva strong',
    'bere bruna silva',
    'bere bruna staropramen',
    'bere carlsberg',
    'bere pasteurizata zimbru',
    'bere heineken',
    'bere albacher',
    'bere heineken',
    'bere alba nefiltrata franziskaner weissbier',
    'bere zimbru',
    'bere artizanala hobgoblin gold',
    'bere karpackie',
    'bere efes malt',
    'bere heineken silver',
    'bere timisoreana',
    'bere peroni nastro azzurra',
    'bere bruna silva strong',
    'bere carlsberg',
    'bere ursus',
    'bere heineken',
    'bere alba paulaner nefiltrata sticla',
    'bere alba nefiltrata paulaner',
    'bere neagra ursus',
    'bere bruna nefiltrata sandro alcool',
    'bere berliner k pilsner',
    'bere birra moretti',
    'bere alba nefiltrata edelweiss',
    'bere schofferhofer grapefruit sticla',
    'bere csiki sor',
    'bere ciucas',
    'bere ciucas',
    'bere nepasteurizata zaganu sticla',
    'bere timisoreana',
    'bere albacher blonda',
    'bere desperados',
    'bere neumarkt',
    'bere nefiltrata weihenstephaner',
    'bere neumarkt',
    'bere neumarkt',
    'bere timisoreana',
    'bere bergenbier blonda',
    'bere lowenbrau blonda',
    'bere alba nefiltrata nenea iancu sticla',
    'bere konig ludwig weissbier hell',
    'bere albacher',
    'bere kozel',
    'bere staropramen',
    'bere ciuc',
    'bere carlsberg sticla',
    'bere dab export',
    'bere nepasteurizata ursus retro',
    'bere aramie eichbaum',
    'bere albrau',
    'bere radeberger pilsner',
    'bere estrella damm',
    'bere kozel',
    'bere neagra ursus',
    'bere timisoreana',
    'bere bruna guinness stout',
    'bere bergenbier',
    'bere stella artois',
    'bere brau',
    'bere ciuc',
    'bere bavaria fara gluten sticla',
    'bere alba nefiltrata hop rider ipa',
    'bere solca',
    'bere artizanala grivita hawai ipa alcool',
    'bere alba nefiltrata hop rider wheat pale ale',
    'bere rosie ipa primator alcool',
    'bere rosie bishops finger sticla',
    'bere rosie spitfire sticla',
    'bere aramie nepasteurizata grivita hazy ipa alcool',
    'bere artizanala hobgoblin',
    'bere nefiltrata erdinger urweisse alcool',
    'bere ciucas',
    'bere carlsberg',
    'bere kozel',
    'bere neagra kozel',
    'bere tuborg',
    'bere heineken silver',
    'bere corona extra',
    'bere zaganu',
    'bere alba zaganu',
    'bere tuborg',
    'bere leffe',
    'bere kozel',
    'bere neagra kozel',
    'bere ciucas',
    'bere heineken',
    'bere tuborg',
    'bere beck',
    'bere tuborg',
    'bere fara alcool timisoreana',
    'bere fara alcool brau',
    'bere fara alcool aroma grapefruit clausthaler',
    'bere fara alcool peroni',
    'bere fara alcool aroma rodie karamalz',
    'bere fara alcool aroma zmeura afine',
    'bere fara alcool clausthaler',
    'bere fara alcool albrau',
    'bere fara alcool bergenbier',
    'bere fara alcool aroma grapefruit bergenbier',
    'bere fara alcool aroma lamaie ciuc radler',
    'bere fara alcool aroma lamie portocale',
    'bere fara alcool aroma zmeura ciuc radler',
    'bere fara alcool timisoreana',
    'bere fara alcool aroma soc edelmeister',
    'bere fara alcool aroma grapefruit lomza radler',
    'bere fara alcool carlsberg',
    'bere fara alcool aroma cirese ursus cooler',
    'bere fara alcool aroma grepefruit ursus cooler',
    'bere fara alcool aroma lamaie ursus cooler',
    'bere fara alcool aroma mango lime ursus cooler',
    'bere fara alcool ursus cooler',
    'bere fara alcool ghimbir bundaberg',
    'bere fara alcool paulaner nefiltrata sticla',
    'bere fara alcool ghimbir caribia',
    'bere fara alcool zmeura ciuc radler',
    'bere fara alcool lamaie ciuc radler',
    'bere fara alcool aroma ghimbir bundaberg',
    'pachet bere ursus cooler doze',
    'cidru dacic aroma lamaie menta',
    'cidru strongbow aroma fructe padure',
    'cidru strongbow aroma coacaze negre',
    'cidru brut val france aroma mere',
    'cidru strongbow aroma coacaze negre',
    'cidru somersby aroma pere',
    'cidru dacic aroma zmeura',
    'cidru somersby aroma afine',
    'cidru dacic aroma afine',
    'cidru dacic aroma cirese',
    'cidru strongbow aroma pere',
    'cidru strongbow aroma fructe padure',
    'cidru strongbow gold aroma mere',
    'cidru somersby aroma mure',
    'cidru somersby aroma mere',
    'cidru dacic aroma capsuni fragute',
    'vin alb demidulce',
    'vin val duna muscat ottonel alb demisec',
    'rigla plastic transparenta pigna hello kitty cm',
    'vin alb sec',
    'vin alb dulce',
    'vin alb demisec',
    'vin alb semidulce cricova chardonnay',
    'vin alb certa cameleon sauvignon blanc chardonnay',
    'vin alb sec',
    'vin sec sauvignon blanc zghihara husi',
    'vin ecologic rosu demisec domeniul bogdan merlot',
    'vin rosu purcari cabernet sauvignon',
    'vin rosu demidulce',
    'caii letea cabernet sauvignon feteasca neagra sec',
    'vin corcova cupaj sec',
    'vin corcova feteascaneagra rosu sec',
    'vin rosu demisec',
    'vin rosu sec',
    'vin sec budureasca merlot',
    'vin rosu dulce',
    'vin rosu domeniile davidescu feteasca neagra malbec',
    'vin rose demisec maiastru cupaj',
    'vin rose sec caii letea roze',
    'vin rose sec',
    'vin ecologic roze demisec domeniul bogdan',
    'vin rose demisec euforia busuioaca alcool',
    'vin roze demidulce',
    'vin rose sec busuioaca averesti',
    'vin roze demisec',
    'vin roze sec',
    'vin rose sec mysterium roze',
    'vin spumant demidulce banfi rosa regale brachetto',
    'vin rose dulce vin chocolate',
    'vin rose demisec domeniile davidescu sorginte rose',
    'vin rose sec domeniile davidescu rara neagra',
    'vin spumant zarea alcool',
    'prosecco grande vento roze',
    'sampanie',
    'vin spumant alb dulce angelli gran dolce',
    'spumant zarea demisec alb',
    'vin spumant brut piper heidsieck alcool',
    'vin spumant demisec piper heidsieck riviera alcool',
    'vin spumant demisec piper heidsieck alcool',
    'spumant brut crisecco roze sec',
    'vin spumant alb sec',
    'spumant zarea crystal collection demisec alb',
    'vin spumant alb demisec',
    'vin spumant rose',
    'vin spumant extra brut piper heidsieck alcool',
    'vin spumant fruits collection gust capsuni zarea',
    'vin spumant fruits collection gust piersica zarea',
    'vin spumant martini asti',
    'vin spumant roze demidulce zarea lambrusco',
    'vin spumant roze dulce angelli cocktail piersici',
    'vin spumant roze sec angelli rose noires',
    'spumant zarea fine moments pahare',
    'vin spumant roze martini sparkling rose',
    'vin spumant zarea royal gold alcool',
    'vin petiant rose sec zarea proseco alcool',
    'vin spumant roze dulce angelli cocktail capsuni',
    'vin spumant alb martini asti alcool',
    'aperitiv campari alc',
    'alcool rafinat prodvin volum alcool',
    'bautura aperitiv campari',
    'bautura spirtoasa jagermeister',
    'jagermeister manifest',
    'lichior cafea sheridan',
    'rachiu pere para prodvinalco',
    'set toiuri afinata visinata bran',
    'bautura spirtoasa monopol',
    'bautura spirtoasa prodvinalco v',
    'rachiu pere prodvinalco',
    'bautura aperitiv aperol',
    'alcool rafinat prodvinalco',
    'bautura alcoolica jagermeister',
    'martini fiero alcool',
    'vermut martini bianco',
    'palinca zalau aciu',
    'palinca mere',
    'palinca prune maramures',
    'horinca maramures prune',
    'horinca maramures prune',
    'bautura spirtoasa saniuta',
    'horinca prune chechis',
    'bautura spirtoasa alba v',
    'bautura spirtoasa prodvinalco r',
    'bautura spirtoasa saniuta',
    'aperitiv carpaten bitter zarea',
    'aperitiv florentino zarea visine',
    'tuica prune vlad tepes alcool',
    'vermut garrone bianco alcool',
    'palinca prune bran',
    'vermut martini rosso alc',
    'aperitiv angelli cherry',
    'brandy vecchia romagna alcool',
    'vinars vinaria bardar ani',
    'coniac cricova divin ani alcool',
    'bautura spirtoasa cava d oro',
    'brandy metaxa',
    'bautura spirtoasa zarea stele',
    'coniac cricova divin ani alcool',
    'bautura spirtoasa alexandrion stele',
    'coniac hennessy vsop alcool',
    'coniac martell',
    'coniac kvint ani',
    'coniac zarea stele',
    'coniac hennessy',
    'vinars brancoveanu v.s o.p',
    'bautura spirtoasa remy martin',
    'bautura spirtoasa unirea',
    'pachet pentru cadou jidvei vinars vsop pahare',
    'jidvei vinars vsop',
    'vinars brancoveanu xo carte',
    'vinars miorita xo ani',
    'vinars prince d arignac armagnac xo',
    'coniac courvoisier alcool',
    'vodca absolut',
    'vodca absolut alcool',
    'vodca absolut alcool',
    'vodka vodca votca',
    'gin',
    'rom captain morgan',
    'rom havana',
    'rom premium el ron prohibido reserva ani alcool',
    'havana club rom yo alcool',
    'rom alb bacardi carta blanca',
    'rom bacardi spiced alcool',
    'rom brugal anejo superior alcool',
    'rom bumbu',
    'rom malibu original aroma cocos',
    'rom canerock alcool',
    'rom plantation x.o alcool',
    'rom bacardi cuatro alcool',
    'bacardi reserva ocho rom alcool',
    'rom plantation original dark alcool',
    'rom zacapa ani alcool pahare incluse',
    'rom bacardi carta negra alcool',
    'tequila',
    'tequilla camino real',
    'tequilla gold jose cuervo especial',
    'pachet pentru cadou whisky j&b rare alcool pahare',
    'whisky johnnie walker',
    'chivas regal whiskey yo alcool',
    'irish whisky jameson',
    'irish whisky jameson',
    'blended whisky akashi japanese',
    'whisky jack danielapple alcool',
    'jameson irish whiskey alcool',
    'whisky jack danieltennessee honey',
    'scotch whisky tennessee jack daniel',
    'scotch whisky ballantine',
    'irish whisky jameson',
    'scotch whisky singleton of dufftown',
    'whisky bulleit bourbon alcool',
    'scotch whisky dimple',
    'scotch whisky chivas regal alcool',
    'blended scotch whisky chivas regal',
    'whiskey jack daniel',
    'rare whisky j&b',
    'scotch whiskey glenfiddich',
    'scotch whisky ballantinefinest',
    'scotch whisky ballantinefinest',
    'scotch whisky label classic black',
    'whisky glenmorangie lasanta ani alcool',
    'whisky j&b rare alcool',
    'whisky j&b rare alcool',
    'whisky jack danieltennessee honey',
    'whisky royal salute ani',
    'whisky chivas regal ani',
    'whisky glenmorangie ruban ani alcool',
    'whisky glenmorangie lasanta ani alcool',
    'whisky jack danielsingle barrel',
    'whisky ballantineblended scotch',
    'pachet pentru cadou tatratea black lichior',
    'irish cream bailey',
    'bacardi breezer aroma portocala',
    'bacardi lime breezer',
    'lichior jagermeister',
    'cocktail mionetto il ugo alb',
    'lichior williams alcool',
    'lichior zarea royal cream ciocolata',
    'crema whisky zarea royal',
    'lichior cafea ciocolata alba sheridan',
    'lichior crema tiramisu angelli',
    'bumbu cream alcool',
    'lichior disaronno originale',
    'lichior mozart ciocolata',
    'bautura spirtoasa drobeta',
    'lichior crema ciocolata angelli',
    'cocktail hugo gioiosa alc',
    'lichior garrone limoncello',
    'dorfer',
    'sangria',
    'cognac',
    'whisky',
    'lichior',
    'ursus',
    'gin',
    'breezer',
    'peroni',
    'rom',
    'ouzo',
    'codru',
    'tuborg',
    'bere',
]

allWhitelists = {
    'legume': whitelistLegume,
    'carne': whitelistCarne,
    'mezeluri': whitelistMezeluri,
    'lactate': whitelistLactate,
    'bauturiNonAlcoolice': whitelistBauturiNonalcoolice,
    'bauturiAlcoolice': whitelistBauturiAlcoolice,
}
